-- QUERY DE EXTRAÇÃO PARA O PAINEL
-- Quando atualizar o banco, necessário atualizar o schema
-- STATUS DE ESTABELECIMENTOS E PROFISSIONAIS
SELECT 
	a.co_unidade,
	a.co_cnes,
	a.co_cnes::int8 AS co_cnes_num,
	a.tp_pfpj,
	a.nivel_dep,
	a.no_razao_social,
	a.no_fantasia,
	a.no_logradouro,
	a.nu_endereco,
	a.no_complemento,
	a.no_bairro,
	a.co_cep,
	a.nu_telefone,
	a.no_email,
	a.nu_cpf,
	a.nu_cnpj,
	a.co_atividade,
	a.co_clientela,
	a.tp_unidade,
	a.co_turno_atendimento,
	a.co_estado_gestor,
	a.co_municipio_gestor,
	a.dt_atualizacao,
	a.co_usuario,
	a.co_cpfdiretorcln,
	a.reg_diretorcln,
	a.st_adesao_filantrop,
	a.co_motivo_desab,
	a.nu_latitude,
	a.nu_longitude,
	a.dt_atu_geo,
	a.no_usuario_geo,
	a.co_natureza_jur,
	a.tp_estab_sempre_aberto,
	a.st_conexao_internet,
	a.co_tipo_unidade,
	a.no_fantasia_abrev,
	a.tp_gestao,
	a.dt_atualizacao_origem,
	a.co_tipo_estabelecimento,
	a.co_atividade_principal,
	a.st_contrato_formalizado,
	a.ds_tipo_estabelecimento,
	a.ds_clientela,
	a.ds_atividade_principal,
	a.ds_tp_gestao,
	a.ds_pfpj,
	a.ds_nivel_dep,
	a.ds_tipo_unidade,
	a.ds_turno_atendimento,
	sum(b.cirurgioes_dentistas) AS cirurgiões_dentistas,
	sum(b.enfermeiros) AS enfermeiros,
	sum(b.medicos) AS medicos
FROM cnes.cnes_202407 AS a
LEFT JOIN cnes.vw_profissionais AS b
	ON a.co_unidade = b.co_unidade 
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 
			15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 
			27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 
			39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50;